### ISSUE TITLE
Skipping tests on a dependency isn't working

### ISSUE THREAD

**Issue by andrew** [dependencyci/dotyaml#2]
See https://github.com/dependencyci/support/issues/26

**Comment by alloy** [comment]
Exciting! 😄 

Re https://github.com/artsy/emission/pull/203

**Comment by andrew** [comment]
Fixed it now, was an issue with case sensitivity and symbols/strings, have reran this build and it passes now: https://dependencyci.com/github/artsy/emission/builds/13

**Comment by fabian** [comment]
Build still failing for me: https://dependencyci.com/github/worldskills/worldskills-events/builds/7

Related [dependencyci.yaml](https://github.com/worldskills/worldskills-events/blob/10a1c80da0c6041a7009585c517f4f8ca129115a/dependencyci.yml) using `type: development`.

**Comment by andrew** [comment]
@fabian will check that for you now

**Comment by andrew** [comment]
@fabian just deploying a fix for that now, the documentation didn't match what the code was doing (`types` vs `type`) so I've updated the code to match the docs, should skip those for you correctly on your next build.

**Comment by fabian** [comment]
@andrew Worked perfectly, thanks a lot for the speedy fix! 🙇

**Comment by alloy** [comment]
@andrew Awesome, thanks!
